name: Block Direct Pushes

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  block-direct-push:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          echo "Direct pushes to protected branches are not allowed"
          exit 1
